### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by BlessedBoy16** [BlessedBoy16/CinemaClub#1]
## 1. Базы данных.
  - [ ] Подключить firebase.
  - [ ] Настроить локальное хранение данных.
 
## 2. Экраны.
  - [ ] Сделать экран с регистрацией пользователя.
  - [ ] Сделать экран с бонусной программой.
